name: sphinx

on: [push, pull_request]  # No need to limit to certain branches
jobs:
  your-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          ref: main
      - name: multipages
        uses: coderefinery/gh-pages-multibranch@main
        if: ${{ github.event_name == 'push' }}
        with:
          directory: public
      # Remember to not limit your deploy step to the default branch!
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/
          force_orphan: true
